version: "3.9"

services:
  authdb:
    image: postgres:15-alpine3.17
    environment:
      POSTGRES_DB: auth_main
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: testee
    ports:
      - "5432:5432"

  redis:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8001:8001
    environment:
      REDIS_ARGS: --requirepass dev_pass
    volumes:
      - redis_data:/data

volumes:
  redis_data:
