version: "3"

tasks:
  build:
    cmds:
      - go build -o ./build/auth ./cmd/auth/main.go
  generate:
    cmds:
      - go generate ./...
  test:
    cmds:
      - go test -cover ./...
  coverage:
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out
  test_with_db:
    cmds:
      - docker container rm -f auth-test-db
      - docker run --name auth-test-db -p 5433:5432 -e POSTGRES_PASSWORD=testee -e POSTGRES_USER=tester -e POSTGRES_DB=testdb -d postgres:15-alpine
      - set -euo pipefail && go test -json -v ./... 2>&1 | tee /tmp/gotest.log | gotestfmt 
