version: "3"

tasks:
  build:
    cmds:
      - go build -o ./build/auth ./cmd/auth/main.go
  generate:
    cmds:
      - go generate ./...
  test:
    cmds:
      - go test -cover ./...
  coverage:
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out
