// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	models "github.com/djordjev/auth/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// RepositoryForgetPassword is an autogenerated mock type for the RepositoryForgetPassword type
type RepositoryForgetPassword struct {
	mock.Mock
}

type RepositoryForgetPassword_Expecter struct {
	mock *mock.Mock
}

func (_m *RepositoryForgetPassword) EXPECT() *RepositoryForgetPassword_Expecter {
	return &RepositoryForgetPassword_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: userId
func (_m *RepositoryForgetPassword) Create(userId uint) (models.ForgetPassword, error) {
	ret := _m.Called(userId)

	var r0 models.ForgetPassword
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (models.ForgetPassword, error)); ok {
		return rf(userId)
	}
	if rf, ok := ret.Get(0).(func(uint) models.ForgetPassword); ok {
		r0 = rf(userId)
	} else {
		r0 = ret.Get(0).(models.ForgetPassword)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryForgetPassword_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type RepositoryForgetPassword_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - userId uint
func (_e *RepositoryForgetPassword_Expecter) Create(userId interface{}) *RepositoryForgetPassword_Create_Call {
	return &RepositoryForgetPassword_Create_Call{Call: _e.mock.On("Create", userId)}
}

func (_c *RepositoryForgetPassword_Create_Call) Run(run func(userId uint)) *RepositoryForgetPassword_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *RepositoryForgetPassword_Create_Call) Return(request models.ForgetPassword, err error) *RepositoryForgetPassword_Create_Call {
	_c.Call.Return(request, err)
	return _c
}

func (_c *RepositoryForgetPassword_Create_Call) RunAndReturn(run func(uint) (models.ForgetPassword, error)) *RepositoryForgetPassword_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: token
func (_m *RepositoryForgetPassword) Delete(token string) (models.ForgetPassword, error) {
	ret := _m.Called(token)

	var r0 models.ForgetPassword
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (models.ForgetPassword, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) models.ForgetPassword); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(models.ForgetPassword)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryForgetPassword_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type RepositoryForgetPassword_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - token string
func (_e *RepositoryForgetPassword_Expecter) Delete(token interface{}) *RepositoryForgetPassword_Delete_Call {
	return &RepositoryForgetPassword_Delete_Call{Call: _e.mock.On("Delete", token)}
}

func (_c *RepositoryForgetPassword_Delete_Call) Run(run func(token string)) *RepositoryForgetPassword_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *RepositoryForgetPassword_Delete_Call) Return(request models.ForgetPassword, err error) *RepositoryForgetPassword_Delete_Call {
	_c.Call.Return(request, err)
	return _c
}

func (_c *RepositoryForgetPassword_Delete_Call) RunAndReturn(run func(string) (models.ForgetPassword, error)) *RepositoryForgetPassword_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepositoryForgetPassword creates a new instance of RepositoryForgetPassword. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoryForgetPassword(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoryForgetPassword {
	mock := &RepositoryForgetPassword{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
