// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	models "github.com/djordjev/auth/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// RepositoryVerifyAccount is an autogenerated mock type for the RepositoryVerifyAccount type
type RepositoryVerifyAccount struct {
	mock.Mock
}

type RepositoryVerifyAccount_Expecter struct {
	mock *mock.Mock
}

func (_m *RepositoryVerifyAccount) EXPECT() *RepositoryVerifyAccount_Expecter {
	return &RepositoryVerifyAccount_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: token, userId
func (_m *RepositoryVerifyAccount) Create(token string, userId uint) (models.VerifyAccount, error) {
	ret := _m.Called(token, userId)

	var r0 models.VerifyAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(string, uint) (models.VerifyAccount, error)); ok {
		return rf(token, userId)
	}
	if rf, ok := ret.Get(0).(func(string, uint) models.VerifyAccount); ok {
		r0 = rf(token, userId)
	} else {
		r0 = ret.Get(0).(models.VerifyAccount)
	}

	if rf, ok := ret.Get(1).(func(string, uint) error); ok {
		r1 = rf(token, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryVerifyAccount_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type RepositoryVerifyAccount_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - token string
//   - userId uint
func (_e *RepositoryVerifyAccount_Expecter) Create(token interface{}, userId interface{}) *RepositoryVerifyAccount_Create_Call {
	return &RepositoryVerifyAccount_Create_Call{Call: _e.mock.On("Create", token, userId)}
}

func (_c *RepositoryVerifyAccount_Create_Call) Run(run func(token string, userId uint)) *RepositoryVerifyAccount_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(uint))
	})
	return _c
}

func (_c *RepositoryVerifyAccount_Create_Call) Return(verification models.VerifyAccount, err error) *RepositoryVerifyAccount_Create_Call {
	_c.Call.Return(verification, err)
	return _c
}

func (_c *RepositoryVerifyAccount_Create_Call) RunAndReturn(run func(string, uint) (models.VerifyAccount, error)) *RepositoryVerifyAccount_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function with given fields: token
func (_m *RepositoryVerifyAccount) Verify(token string) (models.VerifyAccount, error) {
	ret := _m.Called(token)

	var r0 models.VerifyAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (models.VerifyAccount, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) models.VerifyAccount); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(models.VerifyAccount)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryVerifyAccount_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type RepositoryVerifyAccount_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - token string
func (_e *RepositoryVerifyAccount_Expecter) Verify(token interface{}) *RepositoryVerifyAccount_Verify_Call {
	return &RepositoryVerifyAccount_Verify_Call{Call: _e.mock.On("Verify", token)}
}

func (_c *RepositoryVerifyAccount_Verify_Call) Run(run func(token string)) *RepositoryVerifyAccount_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *RepositoryVerifyAccount_Verify_Call) Return(verification models.VerifyAccount, err error) *RepositoryVerifyAccount_Verify_Call {
	_c.Call.Return(verification, err)
	return _c
}

func (_c *RepositoryVerifyAccount_Verify_Call) RunAndReturn(run func(string) (models.VerifyAccount, error)) *RepositoryVerifyAccount_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepositoryVerifyAccount creates a new instance of RepositoryVerifyAccount. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoryVerifyAccount(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoryVerifyAccount {
	mock := &RepositoryVerifyAccount{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
