// Code generated by mockery v2.33.0. DO NOT EDIT.

package domain

import mock "github.com/stretchr/testify/mock"

// MockRepositoryForgetPassword is an autogenerated mock type for the RepositoryForgetPassword type
type MockRepositoryForgetPassword struct {
	mock.Mock
}

type MockRepositoryForgetPassword_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryForgetPassword) EXPECT() *MockRepositoryForgetPassword_Expecter {
	return &MockRepositoryForgetPassword_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: token, userId
func (_m *MockRepositoryForgetPassword) Create(token string, userId uint) (ForgetPassword, error) {
	ret := _m.Called(token, userId)

	var r0 ForgetPassword
	var r1 error
	if rf, ok := ret.Get(0).(func(string, uint) (ForgetPassword, error)); ok {
		return rf(token, userId)
	}
	if rf, ok := ret.Get(0).(func(string, uint) ForgetPassword); ok {
		r0 = rf(token, userId)
	} else {
		r0 = ret.Get(0).(ForgetPassword)
	}

	if rf, ok := ret.Get(1).(func(string, uint) error); ok {
		r1 = rf(token, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryForgetPassword_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepositoryForgetPassword_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - token string
//   - userId uint
func (_e *MockRepositoryForgetPassword_Expecter) Create(token interface{}, userId interface{}) *MockRepositoryForgetPassword_Create_Call {
	return &MockRepositoryForgetPassword_Create_Call{Call: _e.mock.On("Create", token, userId)}
}

func (_c *MockRepositoryForgetPassword_Create_Call) Run(run func(token string, userId uint)) *MockRepositoryForgetPassword_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(uint))
	})
	return _c
}

func (_c *MockRepositoryForgetPassword_Create_Call) Return(request ForgetPassword, err error) *MockRepositoryForgetPassword_Create_Call {
	_c.Call.Return(request, err)
	return _c
}

func (_c *MockRepositoryForgetPassword_Create_Call) RunAndReturn(run func(string, uint) (ForgetPassword, error)) *MockRepositoryForgetPassword_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: token
func (_m *MockRepositoryForgetPassword) Delete(token string) (ForgetPassword, error) {
	ret := _m.Called(token)

	var r0 ForgetPassword
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (ForgetPassword, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) ForgetPassword); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(ForgetPassword)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryForgetPassword_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepositoryForgetPassword_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - token string
func (_e *MockRepositoryForgetPassword_Expecter) Delete(token interface{}) *MockRepositoryForgetPassword_Delete_Call {
	return &MockRepositoryForgetPassword_Delete_Call{Call: _e.mock.On("Delete", token)}
}

func (_c *MockRepositoryForgetPassword_Delete_Call) Run(run func(token string)) *MockRepositoryForgetPassword_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRepositoryForgetPassword_Delete_Call) Return(request ForgetPassword, err error) *MockRepositoryForgetPassword_Delete_Call {
	_c.Call.Return(request, err)
	return _c
}

func (_c *MockRepositoryForgetPassword_Delete_Call) RunAndReturn(run func(string) (ForgetPassword, error)) *MockRepositoryForgetPassword_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepositoryForgetPassword creates a new instance of MockRepositoryForgetPassword. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryForgetPassword(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryForgetPassword {
	mock := &MockRepositoryForgetPassword{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
