name: test
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '^1.20.1'

      - name: Run go version
        run: go version

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test -v ./...

    services:
      postgres:
        image: postgres
        ports:
          - 5433:5432
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: tester
          POSTGRES_PASSWORD: testee
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
